# Generated by Django 4.2.4 on 2024-10-24 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0001_init'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Expertise',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='expertise',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('expertise', 'painting')},
        ),
        migrations.AlterModelTable(
            name='expertise',
            table='expertise',
        ),
    ]
