# Generated by Django 4.2.4 on 2024-11-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertiseitem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='author',
        ),
        migrations.AddField(
            model_name='expertise',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Автор'),
        ),
    ]
