# Generated by Django 4.2.4 on 2024-11-05 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='expertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='artwork.expertise', verbose_name='Заказ'),
        ),
    ]
